### ISSUE TITLE
Load logged in user's profile as homepage (when there is a user logged in)

### ISSUE THREAD

**Issue by sam-eng** [agile-dev-assignments/project-setup-team-hatsukaichi-dynamic#171]
Related to the user story #176

**Comment by sam-eng** [comment]
Should have commented earlier, but this is blocked by #329 as reloading the page or anything of the sort will cause an error in ReactStickyHeader.

**Comment by almazhankapan** [comment]
the task is completed, only pr needs to be merged :)
