### ISSUE TITLE
As a user, I want to be able to select, store and display the shows that I am interested in, so that I can keep track of them and filter as needed

### ISSUE THREAD

**Issue by almazhankapan** [agile-dev-assignments/project-setup-team-hatsukaichi-dynamic#183]
## Estimation of work
- 4

## Acceptance criteria
- [x] Create page that displays shows selected by the user
- [x] Display show cover images and link each image to an individual show
- [x] Add show filtering options by progress and streaming platforms
- [x] User can add new shows
- [ ] Shows tied to user's account

**Comment by LevBernstein** [comment]
Hi Alma,
I'm not sure we need this user story. It seems to be covered by user stories #2 and #3.

**Comment by almazhankapan** [comment]
Yes, however, user story #2 mostly is about adding shows to in progress and watched; user story #3 is about filtering; but there is no user story that allows to select shows, display and store (for each user) - the tasks #34 and #30 are connected to this user story (they do not fit into user stories #2 or #3 - btw each task can be related only to one user story)
